-- Question 1 
-- Pull total number of orders that were completed on 18th March 2023
SELECT COUNT(ORDERID) FROM ORDERS
WHERE DATE = '2023-03-18';

-- Question 2
-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name ‘Doe’
SELECT COUNT(ORDERID) FROM ORDERS
WHERE DATE = '2023-03-18' AND FIRSTNAME='John' AND LASTNAME='Doe';

-- Question 3
-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT ORDERID, SUM(REVENUE)/COUNT(ORDERID) AS REVENUE_PER_ORDERID
FROM ORDERS
WHERE DATE '2023-01-%';

-- Question 4
-- Pull the departments that generated less than $600 in 2022
SELECT DEPARTMENT , SUM(REVENUE) AS REV, FROM ORDERS
WHERE DATE = '2022-%-%'
GROUP BY DEPARTMENT
HAVING REV < 600

-- Question 5
-- What is the most and least revenue we have generated by an order
SELECT ORDERID, MAX(REVENUE) AS HIGHEST_REV
FROM ORDERS

SELECT ORDERID, MIN(REVENUE) AS LOWEST_REV 
FROM ORDERS

-- Question 6
-- What were the orders that were purchased in our most lucrative order
SELECT ORDERID, SUM(REVENUE) AS REV FROM ORDERS
ORDER BY REV DESC


